[workspace]
authors = ["Bangalore Shankar Denanath, Chandan <49138440+chandanbsd@users.noreply.github.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "conway-game-of-life-mojo"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
